### ISSUE TITLE
Non-interactive mode not always non-interactive

### ISSUE THREAD

**Issue by erhan-** [dtrx-py/dtrx#12]
The unzip and 7z commands don't seem to have implemented the non-interactive mode if the switch is activated. It works by changing the lines to:

`extract_command = ['7z', 'x', '-y']`

and

`extract_command = ['unzip', '-o', '-q']`

But this way it forces the non-interactive mode without checking for the argument at all. Works in my case/fork but might be different for you. Still this is a bug.

I am writing in this repo because it is the latest active one.

**Comment by noahp** [comment]
Thanks for the report! can you give examples of archives that have this problem? I tested the following and it seemed to work with the noninteractive flag:

```bash
$ 7z a test.7z README.md
$ dtrx --noninteractive test.7z
$ ls -R test          
test:
README.md
$ dtrx --noninteractive test.7z
dtrx: WARNING: extracting /home/noah/dev/github/dtrx/test.7z to test.1
$ ls -R test test.1
test:
README.md

test.1:
README.md
```

Without the `--noninteractive` flag the above operation prompts for selection.

**Comment by erhan-** [comment]
Unfortunately I have no access to the files anymore. I realized later, that I had an old version from Ubuntu package manager instead of the pip version. In both cases I have still replaced this command because I got the error messages about existing files. Maybe they were jar files. Sorry for no conclusive info.
