### ISSUE TITLE
non-interactive mode shouldn't prompt for a password

### ISSUE THREAD

**Issue by dilinger** [dtrx-py/dtrx#14]
As discussed in #5 , when using --noninteractive, dtrx shouldn't prompt for a password.

**Comment by dilinger** [comment]
When dealing with a single passworded archive ("foo.zip"), "dtrx -n foo.zip" should exit with a warning or error instead of waiting for user input.

When dealing with nested archives, (an unpassworded "bar.tar.gz" containing a passworded "foo.zip"), "dtrx -n bar.tar.gz" behavior is currently correct because -n assumes that nested archives should not be unpacked. When told to unpack recursively however (-r), "dtrx -n -r bar.tar.gz" does the wrong thing and prompts the user. So it needs to be able to handle both cases.

**Comment by erhan-** [comment]
Thank you very much for creating this feature request. I think the way you describe it is correct. Maybe I should look also into this and contribute something when I am already using this. I will check if I can spare some time this weekend and have a look at the code and see how might implement this.

**Comment by erhan-** [comment]
Thank you very much. I did not have the time to look into this.

**Comment by dilinger** [comment]
Can probably close this now.

Also, while not really a high priority, it would be nice to see a release (8.2.2) that includes this fix. :)

**Comment by noahp** [comment]
Good call, I'll push a release now.
