### ISSUE TITLE
Fail faster on Windows

### ISSUE THREAD

**Issue by vadim0x60** [dtrx-py/dtrx#30]
I've recently installed `dtrx` on Windows, tried unpacking several archives and failed. Then I looked up the Trove classifiers (defined [here in setup.cfg](https://github.com/dtrx-py/dtrx/blob/master/setup.cfg)) to see that the only operating system listed there is `Operating System :: POSIX` and conclude that Windows isn't supported.

But if Windows isn't supported, perhaps it's better to fail at `pip install` time and not at call time? Add an `assert` statement to the setup script or something. It would also be cool if pip checked Trove classifiers for this sort of thing automatically, but that issue is for a different repo...

**Comment by noahp** [comment]
Thank you for reporting this!

Looks like the incompatibility is `dtrx`'s use of the `fcntl` module, which is not available on Windows (probably some workarounds we could apply, but might not be worth it).

I think I have a fairly crude workaround that should block installing on Windows, I'll push that up!
