### ISSUE TITLE
dtrx warnings

### ISSUE THREAD

**Issue by an-schall** [dtrx-py/dtrx#35]
Sometimes, when calling dtrx like this:

dtrx -rn $FILE

I receive many warnings à la:

`dtrx: WARNING: extracting /data/av-buffer/tmpFilesArchives/VMware-vCenter-Server-Appliance-6.7.0.52000-19300125-patch-FP/ncurses-6.0-10.ph1/usr/share/man/man3/curs_slk.3x.gz to /data/av-buffer/tmpFilesArchives/VMware-vCenter-Server-Appliance-6.7.0.52000-19300125-patch-FP/ncurses-6.0-10.ph1/usr/share/man/man3/curs_slk.3x.2jzoh7vj`

There are dozens of those warnings. What exactly is the meaning of them and does it mean that there are any conflicts?

Thanks

**Comment by an-schall** [comment]
Hi there,

do you had any chance to have a look at the warnings?

Thanks!

**Comment by an-schall** [comment]
Hi there,

just wanted to ask whether you could dig deeper into this as this is a significant issue at our side.

Best,
André

**Comment by ChrisJefferson** [comment]
Is there any way you can tell us how to reproduce this problem?

**Comment by ChrisJefferson** [comment]
I'm going to close this issue, but please feel free to re-open if you can tell us how to reproduce the problem.
